# import userbot by skyzo

from time import sleep

from userbot import CMD_HELP
from userbot import CMD_HANDLER as cmd
from userbot.utils import flicks_cmd


@flicks_cmd(pattern="wibu2(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(0.07)
    await typew.edit("**Sial Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Sekuat Apapun Aku😭**")
    sleep(0.07)
    await typew.edit("**Jika Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Aku Harus Lari🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Cukkk Ada Wibuuu🏃🏻**")
    sleep(0.07)
    await typew.edit("**Argghh Bangkeee!🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Sekencang-Kencangnya🤸🏻**")
    sleep(0.07)
    await typew.edit("**Karena Kita Sedang🤾🏻**")
    sleep(0.07)
    await typew.edit("**Menghadapi Ras Terkuat🤸🏻**")
    sleep(0.07)
    await typew.edit("**Yang Ada Di Dunia🏃🏻**")
    sleep(0.07)
    await typew.edit("**Wibuuuu🪂**")
    sleep(0.07)
    await typew.edit("**Arghhhhhhh🧗🏻**")
    sleep(0.07)
    await typew.edit("**Istrinya Kartun🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu😨**")
    sleep(0.07)
    await typew.edit("**Maaf Wibu🤼‍♂️**")
    sleep(0.07)
    await typew.edit("**Aku Tidak Akan🤾🏻**")
    sleep(0.07)
    await typew.edit("**Mengulanginya Lagi🏃🏻**")
    sleep(0.07)
    await typew.edit("**Tapi Bo'ong🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu, Istri Kartun🪂**")
    sleep(1)
    await typew.edit("**IUHH DEMEN KOK SAMA 2D😖**")


@flicks_cmd(pattern="wibbu(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WI WIII WIIII WIIII.....**")
    sleep(1)
    await typew.edit("__ARGHHH LARI ADA WIBUU!....__")
    sleep(1)
    await typew.edit("`🏃                        🏂`")
    await typew.edit("`🏃                       🏂`")
    await typew.edit("`🏃                      🏂`")
    await typew.edit("`🏃                     🏂`")
    await typew.edit("`🏃   `LARII ADA WIBU`          🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃..Tolong..🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                    🏂`")
    await typew.edit("`🏃                     🏂`")
    await typew.edit("`🏃  Huh-Huh-Huh       🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃          🏂`")
    await typew.edit("`🏃         🏂`")
    await typew.edit("__KOK MAKIN DEKET SI WIBU__")
    sleep(1)
    await typew.edit("`🏃       🏂`")
    await typew.edit("`🏃      🏂`")
    await typew.edit("`🏃     🏂`")
    await typew.edit("`🏃    🏂`")
    await typew.edit("**Untung Ngga Kena Njir**")
    sleep(1)
    await typew.edit("🌟")
    sleep(2)
    await typew.edit("**Mampus Kau Wibu**")


@flicks_cmd(pattern="jadiwibu(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**Kekuatan Mengjadi Wibu Garis Keras**")
    await typew.edit("**Kekuatan Menjadi Wibu Telah Aktif**")
    sleep(3)
    await typew.edit("**Rajin Sholat☑️**")
    await typew.edit("**Rajin Sholat✅**")
    sleep(2)
    await typew.edit("**Tidak Bolos Sekolah☑️**")
    await typew.edit("**Tidak Bolos Sekolah✅**")
    sleep(2)
    await typew.edit("**Gak Sangean☑️**")
    await typew.edit("**Gak Sangean✅**")
    sleep(2)
    await typew.edit("**Harus Sangean☑️**")
    await typew.edit("**Harus Sangean✅**")
    sleep(2)
    await typew.edit("**Tidak Alay☑️**")
    await typew.edit("**Tidak Alay✅**")
    sleep(2)
    await typew.edit("**Suka Membantu☑️**")
    await typew.edit("**Suka Membantu✅**")
    sleep(2)
    await typew.edit("**Selalu Berbagi Duit:v☑️**")
    await typew.edit("**Selalu Berbagi Duit:v✅**")
    sleep(2)
    await typew.edit("**Sukses Menjadi Wibu**")
    sleep(1)
    await typew.edit("**Iya Wibu, Seperti Watashi**")


@flicks_cmd(pattern="adawibu(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WI WIII WIIII**")
    await typew.edit("`🏃.....Wibu Anjir.......🏃`")
    await typew.edit("`🏃....................🏃`")
    await typew.edit("`🏃..................🏃`")
    await typew.edit("`🏃.....`LARII`....🏃`")
    await typew.edit("`🏃..............🏃`")
    await typew.edit("`🏃.............🏃`")
    await typew.edit("`🏃..Anjing...🏃`")
    await typew.edit("`🏃.........🏃`")
    await typew.edit("`🏃..Wiba..🏃`")
    await typew.edit("`🏃...Wibu...🏃`")
    await typew.edit("`🏃......🏃`")
    await typew.edit("`🏃.......🏃`")
    await typew.edit("`🏃.........🏃`")
    await typew.edit("`🏃..Tolong..🏃`")
    await typew.edit("`🏃...........🏃`")
    await typew.edit("`🏃............🏃`")
    await typew.edit("`🏃.............🏃`")
    await typew.edit("`🏃....Watashi...🏃`")
    await typew.edit("`🏃.....Kejar.....🏃`")
    await typew.edit("`🏃.....Sampai.....🏃`")
    await typew.edit("`🏃.....Dapat.......🏃`")
    await typew.edit("`🏃..................🏃`")
    await typew.edit("`🏃......Anjir........🏃`")
    await typew.edit("`🏃....................🏃`")
    await typew.edit("`🏃.....................🏃`")
    await typew.edit("`🏃..Huh-Huh-Huh.......🏃`")
    await typew.edit("`🏃...................🏃`")
    await typew.edit("`🏃..................🏃`")
    await typew.edit("`🏃.................🏃`")
    await typew.edit("`🏃................🏃`")
    await typew.edit("`🏃...............🏃`")
    await typew.edit("`🏃..............🏃`")
    await typew.edit("`🏃.............🏃`")
    await typew.edit("`🏃..Bodoamat..🏃`")
    await typew.edit("`🏃...........🏃`")
    await typew.edit("`🏃..........🏃`")
    await typew.edit("`🏃.........🏃`")
    await typew.edit("__KOK MAKIN DEKET SI.__")
    sleep(1)
    await typew.edit("`🏃.......🏃`")
    await typew.edit("`🏃...Y..🏃`")
    await typew.edit("`🏃.....🏃`")
    await typew.edit("`🏃....🏃`")
    await typew.edit("**Untung Ngga Kena Njir**")
    sleep(1)
    await typew.edit("__Cape Juga Gitu__")
    sleep(2)
    await typew.edit("**Kasian Si Wibu Wokwokwok**")


@flicks_cmd(pattern="turtle(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**War Sama Turtle Kah Gass Lah Ajg**")
    sleep(2)
    await typew.edit("`🐢..🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢...🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢...🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢..🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢......🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢.......🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢.......🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢......🤺`")
    await typew.edit("`🐢....WUISH...🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢...MINGGIR..AJG..🤺`")
    await typew.edit("`🐢............🤺`")
    await typew.edit("`🐢......🤺`")
    await typew.edit("`🐢.......🤺`")
    await typew.edit("`🐢........🤺`")
    await typew.edit("`🐢..HUH-HUH-HUH....🤺`")
    await typew.edit("`🐢........🤺`")
    await typew.edit("`🐢...........🤺`")
    await typew.edit("`🐢.......🤺`")
    await typew.edit("`🐢..........🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢.......🤺`")
    await typew.edit("`🐢.........🤺`")
    await typew.edit("`🐢..🤺`")
    await typew.edit("`🐢......🤺`")
    await typew.edit("`🐢.....🤺`")
    await typew.edit("`🐢...🤺`")
    await typew.edit("__GA MATI MATI ANJ__")
    sleep(1)
    await typew.edit("`🐢......🤺`")
    await typew.edit("`🐢..🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("`🐢....🤺`")
    await typew.edit("**Cling....**")
    sleep(1)
    await typew.edit("**Turtle Telah Di Eliminasi**")
    sleep(2)
    await typew.edit("**Good Game**")


@flicks_cmd(pattern="gbt(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**Wait**")
    await typew.edit(" ▰ ")
    await typew.edit(" ▰▱ ")
    await typew.edit(" ▰▱▰ ")
    await typew.edit(" ▰▱▰▱ ")
    await typew.edit(" ▰▱▰▱▰ ")
    await typew.edit(" ▰▱▰▱▰▱ ")
    await typew.edit(" ▰▱▰▱▰▱▰ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰▱ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰▱▰ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰▱▰▱ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰▱▰▱▰ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰▱▰▱▰▱ ")
    await typew.edit(" ▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰ ")
    await typew.edit(" **Flicks Userbot 🚀** ")
    sleep(1)
    await typew.edit(" **Gunakan Flicks Userbot Sekarang** ")
    sleep(2)
    await typew.edit(" **Ngik Ngok Ngik Ngok** ")


CMD_HELP.update(
    {
        "wibu": f"**Modules** - `wibu`\
        \n\n Cmd : `{cmd}wibbu`\
        \nUsage : ngatain wibu\
        \n\n Cmd : `{cmd}turtle`\
        \nUsage : war sama turtle\
        \n\n Cmd : `{cmd}jadiwibu`\
        \nUsage : untuk jadi wibu\
        \n\n Cmd : `{cmd}gbt`\
        \nUsage : liat sendiri\
        \n\n Cmd : `{cmd}adawibu`\
        \nUsage : lari ada wibu\
        \n\n Cmd : `{cmd}wibu2`\
        \nUsage : ngatain wibu 2\
    "
    }
)
